# Generated by Django 2.0.2 on 2020-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('bookname', models.CharField(max_length=255)),
                ('bookid', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
