# Generated by Django 2.0.2 on 2020-03-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200330_0039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='issue',
            new_name='issuebook',
        ),
    ]
