# Generated by Django 2.0.2 on 2020-03-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_issuebook1'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('clgid', models.IntegerField()),
                ('bookname', models.CharField(max_length=255)),
                ('bookid', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='issuebook1',
        ),
        migrations.DeleteModel(
            name='ret',
        ),
        migrations.RemoveField(
            model_name='issuebook',
            name='password',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='clgid',
            field=models.IntegerField(default=1),
        ),
    ]
